package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Citibank creat account check")
    void generatedTest() {
        step("Open https://www.citi.com/", () -> {
            step("// todo: just add selenium action");
        });

        step("Click on menu \"Open an Account\"", () -> {
            step("// todo: just add selenium action");
        });

        step("\"Apply for an Account\" should be visible", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.citi.com/'", () ->
            open("https://www.citi.com/"));

        step("Page title should have text 'Online Banking, Mortgages, Personal Loans, Investing | Citi.com'", () -> {
            String expectedTitle = "Online Banking, Mortgages, Personal Loans, Investing | Citi.com";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.citi.com/'", () ->
            open("https://www.citi.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}